name: Deployment CI

on:
  push:
    branches:
      - main

jobs:
  Rubocop_and_RSpec:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install and update gems
        run: |
            gem install bundler
            bundle install --without jekyll jekyll_plugins

      - name: Run CI
        run: |
          rubocop
          rspec

      - name: Set environment variables
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          MAIN_COMMIT_HASH=$(git log -1 --format="%h")

      - name: Commit to main
        run: |
          git add .
          git commit -m "GitHub Actions commit. Reflects main branch commit `$MAIN_COMMIT_HASH`"
