name: Build, Test & Deploy

on:
  push:
    branches:
      # - main
      - deployment-test

jobs:
  build_test_deploy:
    runs-on: macos-latest

    env:
      DEPLOY_BRANCH: gh-pages
      DEPLOY_BRANCH_2: gh-pages-2
      DEPLOY_BRANCH_3: gh-pages-3
      DEPLOY_BRANCH_4: gh-pages-4
      DEPLOY_BRANCH_5: gh-pages-5
      TOKEN: ${{ secrets.ACTION_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      # - name: Install Gems
      #   run: |
      #       gem install bundler
      #       bundle install --without jekyll jekyll_plugins

      - name: Set ENV Variables
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com


      # - name: Run Tests
      #     rubocop
      #     rspec

      - name: Commit
        run: |
          echo "Hello World!" >> test.txt
          $DEPLOY_BRANCH
          echo ${{ env.DEPLOY_BRANCH_2 }}
          echo $DEPLOY_BRANCH_2
          echo ${{ DEPLOY_BRANCH_3 }}
          echo ${{ $DEPLOY_BRANCH_4 }}
          git add .
          git commit -am "Automated post-CI deployment commit. Reflects ${{ github.ref }} commit ${{ github.sha }}."

      # - name: Deploy
      #   run: |
      #     git remote set-url origin "https://x-access-token:${{ github.TOKEN }}@github.com/${{ github.repository }}"
