name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test_deploy:
    runs-on: macos-latest

    env:
      EMPLOY_BRANCH: main
      DEPLOY_BRANCH: gh-pages
      DEPLOY_TOKEN: ${{ secrets.ACTIONS_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install Gems
        run: bundle install --without jekyll jekyll_plugins

      - name: Run Tests
        run: |
          rubocop
          rspec

      - name: Edit Commit Message
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --amend -m "Automated post-CI deployment commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }})."

      - name: Fetch Deploy Branch
        run: |
          git remote set-url origin "https://x-access-token:${{ env.DEPLOY_TOKEN }}@github.com/${{ github.repository }}"
          git fetch origin ${{ env.DEPLOY_BRANCH }}

      - name: Reset Deploy Branch
        run: |
          git checkout ${{ env.DEPLOY_BRANCH }}
          git reset --hard ${{  env.EMPLOY_BRANCH }}

      - name: Deploy
        run: git push --force-with-lease origin ${{ env.DEPLOY_BRANCH }}
