name: Build, Test & Deploy

on:
  push:
    branches:
      # - main
      - deployment-test

jobs:
  build_test_deploy:
    runs-on: macos-latest

    env:
      DEPLOY_BRANCH: gh-pages
      TOKEN: ${{ secrets.ACTION_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      # - name: Install Gems
      #   run: bundle install --without jekyll jekyll_plugins

      - name: Set ENV Variables
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com

      # - name: Run Tests
      #   run: |
      #     rubocop
      #     rspec

      - name: Commit
        env:
          PRETTY_HASH: ${{ github.sha }}

        run: |
          var=${{ env.PRETTY_HASH }}
          echo ${var:0:7}
          echo "Hello World!" >> test.txt
          git add .
          git commit -am "Automated post-CI deployment commit. Reflects ${{ github.ref }} commit ${{ var:0:7 }}."

      - name: Deploy
        run: |
          git remote set-url origin "https://x-access-token:${{ env.TOKEN }}@github.com/${{ github.repository }}"
          git remote -v
