name: Build, Test & Deploy

on:
  push:
    branches:
      - push-test

jobs:
  build_test_deploy:
    runs-on: macos-latest

    env:
      DEPLOY_BRANCH: gh-pages
      DEPLOY_TOKEN: ${{ secrets.ACTIONS_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      # - name: Install Gems
      #   run: bundle install --without jekyll jekyll_plugins
      #
      # - name: Run Tests
      #   run: |
      #     rubocop
      #     rspec

      - name: Fetch Branch
        run: |
          git remote set-url origin "https://x-access-token:${{ env.DEPLOY_TOKEN }}@github.com/${{ github.repository }}"
          git fetch origin gh-pages
          git branch -a

      # - name: Commit
      #   run: |
      #     echo Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }}). >> test.txt
      #     git add .
      #     git commit -am "Automated post-CI deployment commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }})."
      #
      # - name: Deploy
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git push --force-with-lease origin ${{ env.DEPLOY_BRANCH }}
