name: Build, Test & Deploy

on:
  push:
    branches:
      - push-test

jobs:
  build_test_deploy:
    runs-on: macos-latest

    env:
      DEPLOY_BRANCH: gh-pages
      TOKEN: ${{ secrets.ACTION_PAT }}
      REPO_URI: "https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Test remote
        run: |
          git remote -v
          echo $REPO_URI
          git remote set-url origin ${{ env.REPO_URI }}
          git remote -v

      # - name: Install Gems
      #   run: bundle install --without jekyll jekyll_plugins
      #
      # - name: Run Tests
      #   run: |
      #     rubocop
      #     rspec

      - name: Commit
        run: |
          echo "Hello World!" >> test.txt
          git add .
          git commit -am "Automated post-CI deployment commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }})."

      - name: Deploy
        run: |
          git remote set-url origin ${{ env.REPO_URI }}
          git push gh-pages
