name: Build, Test & Deploy

on:
  push:
    branches:
      - push-test

jobs:
  build_test_deploy:
    runs-on: macos-latest

    env:
      DEPLOY_BRANCH: gh-pages
      DEPLOY_TOKEN: ${{ secrets.ACTIONS_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      # - name: Install Gems
      #   run: bundle install --without jekyll jekyll_plugins
      #
      # - name: Run Tests
      #   run: |
      #     rubocop
      #     rspec

      - name: Commit
        run: |
          echo Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }}). >> test.txt
          git add .
          git commit -am "Automated post-CI deployment commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }})."

      - name: Deploy
        run: |
          ${{ github.workspace }}
          ${{ github.server_url }}
          ${{ github.actor }}
          git remote set-url origin "https://x-access-token:${{ env.DEPLOY_TOKEN }}@github.com/${{ github.repository }}"
          git push --force-with-lease origin ${{ env.DEPLOY_BRANCH }}
