name: Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test_deploy:
    runs-on: macos-latest

    env:
      EMPLOY_BRANCH: main
      DEPLOY_BRANCH: gh-pages
      DEPLOY_TOKEN: ${{ secrets.ACTIONS_PAT }}
      DIFF_BOOLEAN: true
      COMMIT_USER_NAME: "GitHub Action"
      COMMIT_USER_EMAIL: "github-actions@github.com"
      COMMIT_MESSAGE: Automated commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }}).

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install Gems
        run: |
          bundle config set --local without 'jekyll jekyll_plugins'
          bundle install

      - name: Run Tests
        run: |
          rubocop
          rspec

    # - name: Check For Changes
    #   run: |
    #     if git diff --exit-code; then
    #       echo "DIFF_BOOLEAN=true" >> $GITHUB_ENV
    #     fi

      - name: New Commit If Changes
        if: env.DIFF_BOOLEAN == 'true'
        run: |
          git add .
          git config user.name $COMMIT_USER_NAME
          git config user.email $COMMIT_USER_EMAIL
          git commit -m $COMMIT_MESSAGE

      # - name: Edit Commit If No Changes
      #   if: env.DIFF_BOOLEAN == 'false'
      #   run: git commit --amend --author="$COMMIT_USER_NAME <$COMMIT_USER_EMAIL>" -m $COMMIT_MESSAGE
      #
      # - name: Fetch Deploy Branch
      #   run: |
      #     git remote set-url origin "https://x-access-token:${{ env.DEPLOY_TOKEN }}@github.com/${{ github.repository }}"
      #     git fetch origin ${{ env.DEPLOY_BRANCH }}
      #
      # - name: Reset Deploy Branch
      #   run: |
      #     git checkout ${{ env.DEPLOY_BRANCH }}
      #     git reset --hard ${{  env.EMPLOY_BRANCH }}
      #
      # - name: Deploy
      #   run: git push --force-with-lease origin ${{ env.DEPLOY_BRANCH }}
